name: Build macOS App

on:
  push:
    branches: [master]

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install py2app

      - name: Build macOS App
        run: python setup.py py2app

      - name: Upload .app bundle
        uses: actions/upload-artifact@v4
        with:
          name: MacApp
          path: dist/*.app